<!-- JS here -->
<script src="{{ asset('assets/frontend/js/vendor/jquery.js') }}"></script>
<script src="{{ asset('assets/frontend/js/vendor/waypoints.js') }}"></script>
<script src="{{ asset('assets/frontend/js/bootstrap-bundle.js') }}"></script>
<script src="{{ asset('assets/frontend/js/swiper-bundle.js') }}"></script>
<script src="{{ asset('assets/frontend/js/slick.js') }}"></script>
<script src="{{ asset('assets/frontend/js/magnific-popup.js') }}"></script>
<script src="{{ asset('assets/frontend/js/nice-select.js') }}"></script>
<script src="{{ asset('assets/frontend/js/purecounter.js') }}"></script>
<script src="{{ asset('assets/frontend/js/wow.js') }}"></script>
<script src="{{ asset('assets/frontend/js/smooth-scroll.js') }}"></script>
<script src="{{ asset('assets/frontend/js/ajax-form.js') }}"></script>
<script src="{{ asset('assets/frontend/js/imagesloaded-pkgd.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main.js') }}"></script>
